### ISSUE TITLE
Cannot upload the .json to watson

### ISSUE THREAD

**Issue by KimbiyaI** [Botmock/botmock-watson-export#14]
Hey guys, 

I have managed to follow the steps to generate the .json file from botmock. However when i try to upload this file into IBM watson i get an error message "Error

We could not import your Skill. next_step.dialog_node should have a minimum length of 1. " 

Do you guys know what could be the reason for this? 
![Capture](https://user-images.githubusercontent.com/54961575/64498445-a0a6dd00-d308-11e9-9ccd-63b412ef9d40.PNG)

**Comment by nonnontrivial** [comment]
Hi @KimbiyaI ! I've merged a [PR](https://github.com/Botmock/botmock-watson-export/pull/15) that should solve this issue. Can you pull from `master` and confirm that you no longer encounter this error?
